gh-17 adding list and summary function

diff --git a/git-artifact b/git-artifact
--- a/git-artifact
+++ b/git-artifact
@@ -49,6 +49,7 @@ push            push a tag
 add-n-push      add and commit files to repo and then push them
 fetch-co   	    fetch tag from remote and checkout it out
 reset           reset workspace and branches
+list            list all tags in the repo given a glob pattern
 find-latest     Find the latest tags from reqex and print it
 fetch-co-latest Get latest tag form remote using grep reg-ex and reset hard to it
 fetch-tags      Fetch all tags that points to a sha1 or HEAD - Useful in relation to detached HEAD and submodules
@@ -68,8 +69,8 @@ b,branch=     use branch for local changes and pushes
  options for 'add-n-tag', 'push', 'add-n-push', 'fetch-co'
 t,tag=         the tag to be created
 
- options for 'fetch-co-latest', 'find-latest'
-r,regex=       the reg-ex pattern to latest of
+ options for 'fetch-co-latest', 'find-latest', 'list'
+g,glob=       the glob pattern search remote for tags
 
  options for 'fetch-tags'
 s,sha1=       The sha1 of which to get tags from from 
@@ -301,10 +302,46 @@ cmd_fetch-co() {
     git log -1 --oneline --decorate
 }
 
+cmd_list() {
+    if [[ ${arg_quiet:-} -ne 1 ]]; then
+        git ls-remote --tags --ref --sort=v:refname origin  "refs/tags/${arg_glob:-*}" | cut -d / -f 3-
+    fi
+    printf "Tags found: %s : %s\n" "${arg_glob}" "$(git ls-remote --tags --ref --sort=v:refname origin  "refs/tags/${arg_glob:-*}" | wc -l)"
+}
+
+cmd_summary() {
+    # set if it is unset
+   : "${delimiter:=/}"
+    declare -A tags
+    read_remote_tags_to_map tags
+    echo "Summary of of amount of tags in using delimiter: ${delimiter} and filter on first column"
+    echo "----------------------------------------------------------------------------------------"
+ 
+    # Example: print the hash map
+    for k in "${!tags[@]}"; do
+        amount=$(echo -n "${tags[$k]}" | wc -l)
+        echo "$k : ${amount}"
+    done
+}
+
+read_remote_tags_to_map() {
+   local -n _tags=${1}
+   # set if it is unset
+   : "${delimiter:=/}"
+
+    while read -r line; do
+        # Extract the tag name from the line
+        key="${line#*refs/tags/}"
+        key="${key%%/*}"
+        info="${line#*$delimiter}"
+        _tags["$key"]+="$info"$'\n'
+    done < <(git ls-remote --tags --ref --sort=v:refname refs/tags/*)
+}
+
 find-latest() {
     local -n _latest_tag=${1}
     # https://stackoverflow.com/questions/10649814/get-last-git-tag-from-a-remote-repo-without-cloning
-    _latest_tag=$(git ls-remote --tags --refs --sort='-version:refname' origin ${arg_regex} | head -n 1 | cut  -f2 | cut -d / -f3-) || {
+    _latest_tag=$(git ls-remote --tags --refs --sort='-version:refname' origin ${arg_glob} | head -n 1 | cut  -f2 | cut -d / -f3-) || {
         local exit_code=$?
         if [[ $exit_code -ne 141 ]]; then 
             #https://unix.stackexchange.com/questions/580117/debugging-sporadic-141-shell-script-errors
@@ -313,7 +350,7 @@ find-latest() {
         fi
     } 
     if [ -z "${_latest_tag:-}" ]; then 
-        echo "ERROR: No tag found using regex: ${arg_regex} "
+        echo "ERROR: No tag found using glob pattern: ${arg_glob} "
         exit 1
     fi
 }
@@ -366,7 +403,7 @@ main () {
 
         case "$opt" in
         -q)
-            GIT_QUIET=1
+            arg_quiet=1
             ;;
         -d)
             arg_debug=1
@@ -387,8 +424,8 @@ main () {
             arg_path="$1"
             shift
             ;;
-        --regex|-r)
-            arg_regex="$1"
+        --glob|-g)
+            arg_glob="$1"
             shift
             ;;
         --sha1|-s)
@@ -405,6 +442,7 @@ main () {
     done
     arg_command=$1
     shift
+
     which git-sh-setup
     case "$arg_command" in
         init)	if test -z "${arg_remoteurl:-}"  ; then
@@ -461,15 +499,21 @@ main () {
                 . git-sh-setup
                 require_work_tree
                 ;;
-        fetch-co-latest|find-latest)
+        fetch-co-latest|find-latest|list)
                 # shellcheck source=/dev/null
                 . git-sh-setup
                 require_work_tree
-                if test -z "${arg_regex:-}"  ; then
+                
+                if test -z "${arg_glob:-}"  ; then
                     git artifact -h
-                    echo "ERROR: -r|--regex is required for $arg_command"
+                    echo "ERROR: -g|--glob is required for $arg_command"
                     exit 1
                 fi
+                ;;
+        summary)
+                # shellcheck source=/dev/null
+                . git-sh-setup
+                require_work_tree
                 ;;
         fetch-tags)
                 # shellcheck source=/dev/null
@@ -486,7 +530,7 @@ main () {
                 ;;
     esac
     debug "command: {$arg_command}"
-    debug "quiet: {$GIT_QUIET}"
+    debug "quiet: {${arg_quiet:-0}}"
     debug "opts: {$*}"
     debug
 
