gh-15 : change shabang for compatibility and test for bash 4.3+

diff --git a/git-artifact b/git-artifact
--- a/git-artifact
+++ b/git-artifact
@@ -1,7 +1,21 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # git-artifact: use a git repository as artifact management storage
 #
+if [[ "${BASH_VERSINFO:-}" == "" ]] ; then
+    echo "ERROR: git-artifact only runs in bash - pleaes check that the variable"
+    echo "       is set"
+    echo "BASH_VERSINFO: ${BASH_VERSINFO:-unknown}"
+    echo "BASH_VERSION: ${BASH_VERSION:-unknown}"
+    exit 1
+fi
+
+if [[ "${BASH_VERSINFO[0]}" -eq 4 && "${BASH_VERSINFO[1]}" -lt 3 ]]; then
+    echo "ERROR: git-artifact requires Bash version 4.3 or higher."
+    echo "BASH_VERSINFO: ${BASH_VERSINFO:-unknown}"
+    echo "BASH_VERSION: ${BASH_VERSION:-unknown}"
+    exit 1
+fi
 
 if test -z "$GIT_EXEC_PATH" || ! test -f "$GIT_EXEC_PATH/git-sh-setup" || {
     test "${PATH#"${GIT_EXEC_PATH}:"}" = "$PATH" &&
@@ -9,8 +23,7 @@ if test -z "$GIT_EXEC_PATH" || ! test -f "$GIT_EXEC_PATH/git-sh-setup" || {
 }
 then
     basename=${0##*[/\\]}
-    echo >&2 'It looks like either your git installation or your'
-    echo >&2 'git-subtree installation is broken.'
+    echo >&2 'It looks like your git installation broken'
     echo >&2
     echo >&2 "Tips:"
     echo >&2 " - If \`git --exec-path\` does not print the correct path to"
